package demo.persons.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_PersonRef;
  private ConceptPresentation props_Persons;
  private ConceptPresentation props_PersonsContainer;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.PersonRef:
        if (props_PersonRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x4832870850814e8cL, 0x8f0506019d4c5f64L, 0x139c3e965b3bb628L, 0x139c3e965b3bb62aL, "person", "", "");
          props_PersonRef = cpb.create();
        }
        return props_PersonRef;
      case LanguageConceptSwitch.Persons:
        if (props_Persons == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Persons = cpb.create();
        }
        return props_Persons;
      case LanguageConceptSwitch.PersonsContainer:
        if (props_PersonsContainer == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          cpb.icon(IconContainer.RESOURCE_0);
          props_PersonsContainer = cpb.create();
        }
        return props_PersonsContainer;
    }
    return null;
  }
}
