package demo.persons.structure;

/*Generated by MPS */

import jetbrains.mps.annotations.ResourceModule;
import jetbrains.mps.smodel.runtime.IconResource;

@ResourceModule("48328708-5081-4e8c-8f05-06019d4c5f64(demo.persons)")
public class IconContainer {
  protected static IconResource RESOURCE_0 = new IconResource("TextIcon_1.png", null, IconContainer.class);
}
