package demo.persons.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int PersonRef = 0;
  public static final int Persons = 1;
  public static final int PersonsContainer = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x4832870850814e8cL, 0x8f0506019d4c5f64L);
    builder.put(0x139c3e965b3bb628L, PersonRef);
    builder.put(0x222e912402a02fdbL, Persons);
    builder.put(0x222e912402a02fc3L, PersonsContainer);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
