package demo.persons.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptPersonRef = createDescriptorForPersonRef();
  /*package*/ final ConceptDescriptor myConceptPersons = createDescriptorForPersons();
  /*package*/ final ConceptDescriptor myConceptPersonsContainer = createDescriptorForPersonsContainer();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptPersonRef, myConceptPersons, myConceptPersonsContainer);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.PersonRef:
        return myConceptPersonRef;
      case LanguageConceptSwitch.Persons:
        return myConceptPersons;
      case LanguageConceptSwitch.PersonsContainer:
        return myConceptPersonsContainer;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForPersonRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("demo.persons", "PersonRef", 0x4832870850814e8cL, 0x8f0506019d4c5f64L, 0x139c3e965b3bb628L);
    b.class_(false, false, false);
    b.origin("r:968ce677-0b51-4ac1-9c3d-6912cd64b936(demo.persons.structure)/1413073198584149544");
    b.version(3);
    b.associate("person", 0x139c3e965b3bb62aL).target(0x4832870850814e8cL, 0x8f0506019d4c5f64L, 0x222e912402a02fdbL).optional(false).origin("1413073198584149546").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPersons() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("demo.persons", "Persons", 0x4832870850814e8cL, 0x8f0506019d4c5f64L, 0x222e912402a02fdbL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:968ce677-0b51-4ac1-9c3d-6912cd64b936(demo.persons.structure)/2463065630067142619");
    b.version(3);
    b.property("birthYear", 0x139c3e965b4055afL).type(PrimitiveTypeId.INTEGER).origin("1413073198584452527").done();
    b.property("birthLocation", 0x139c3e965b4055b0L).type(PrimitiveTypeId.STRING).origin("1413073198584452528").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPersonsContainer() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("demo.persons", "PersonsContainer", 0x4832870850814e8cL, 0x8f0506019d4c5f64L, 0x222e912402a02fc3L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:968ce677-0b51-4ac1-9c3d-6912cd64b936(demo.persons.structure)/2463065630067142595");
    b.version(3);
    b.aggregate("persons", 0x222e912402a02fddL).target(0x4832870850814e8cL, 0x8f0506019d4c5f64L, 0x222e912402a02fdbL).optional(true).ordered(true).multiple(true).origin("2463065630067142621").done();
    return b.create();
  }
}
