package demo.persons.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class PersonRef_SubstituteMenu extends SubstituteMenuBase {
  public PersonRef_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for PersonRef. Generated from implicit smart reference attribute.", new SNodePointer("r:968ce677-0b51-4ac1-9c3d-6912cd64b936(demo.persons.structure)", "1413073198584149544")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_ntu8t_a(), CONCEPTS.PersonRef$j9));
    result.add(new SMP_Subconcepts_ntu8t_b());
    return result;
  }

  public class SMP_ReferenceScope_ntu8t_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_ntu8t_a() {
      super(CONCEPTS.PersonRef$j9, LINKS.person$SM5K, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_ntu8t_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_ntu8t_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "PersonRef", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.PersonRef$j9);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept PersonRef$j9 = MetaAdapterFactory.getConcept(0x4832870850814e8cL, 0x8f0506019d4c5f64L, 0x139c3e965b3bb628L, "demo.persons.structure.PersonRef");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink person$SM5K = MetaAdapterFactory.getReferenceLink(0x4832870850814e8cL, 0x8f0506019d4c5f64L, 0x139c3e965b3bb628L, 0x139c3e965b3bb62aL, "person");
  }
}
